### ISSUE TITLE
Should be possible change network tier

### ISSUE THREAD

**Issue by willwv** [terraform-google-modules/terraform-google-lb-http#369]
### TL;DR

This terraform resource creates by default a global load balancer with premium network tier but it should be possible to choose between premium and default in the front-end settings.

**Comment by imrannayer** [comment]
@willwv I dont see any variable in `google_compute_global_forwarding_rule`? Can you plz provide more details about this request?

**Comment by CptKirk** [comment]
Hi there, although I'm not the original creator of the issue, I believe I can shed some light on the matter as I'm encountering the same problem. The core issue arises from the usage of the `google_compute_global_forwarding_rule` and `google_compute_global_address` resources within this module. These resources inherently operate at the premium tier by default and lack the capability to set the network_tier. This limitation is explicitly addressed in the regional equivalents of these resources, as seen in the documentation for [`google_compute_forwarding_rule`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_forwarding_rule#network_tier) and [`google_compute_address`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_address#network_tier).

I might be mistaken, but it can be that not all functionalities of this module can be mirrored in the regional resources, primarily due to my limited understanding of the various load balancer types available in GCE. It's also possible that this falls outside the intended scope of this module, which is described as a "Global HTTP Load Balancer" in the README. However, if it does fall within the scope, I propose that the module should offer an option to choose between regional and global scopes for the load balancer. When opting for the regional variant, users should also have the ability to modify the network tier. Hope this helps in addressing the issue.
