### ISSUE TITLE
Support for HTTP -> HTTPS redirects

### ISSUE THREAD

**Issue by acdha** [terraform-google-modules/terraform-google-lb-http#95]
Now that https://issuetracker.google.com/issues/35904733 has finally shipped it would be neat if an HTTP->HTTPS redirect could be a simple option

**Comment by mercuriete** [comment]
https://cloud.google.com/load-balancing/docs/https/traffic-management

this should be implemented first on google terraform provider?

I would like this asap.

thanks :)

**Comment by mercuriete** [comment]
I think is not implemented yet

https://github.com/terraform-providers/terraform-provider-google/issues/6205

**Comment by Dev25** [comment]
This is now unblocked via provider v3.20.0

https://www.terraform.io/docs/providers/google/r/compute_url_map.html#url_redirect-1
https://www.terraform.io/docs/providers/google/r/compute_url_map.html#default_url_redirect

**Comment by Dev25** [comment]
>This must only be set for UrlMaps used in TargetHttpProxys. Setting this true for TargetHttpsProxy is not permitted.

Example:
https://www.terraform.io/docs/providers/google/r/compute_target_http_proxy.html#example-usage-target-http-proxy-https-redirect

This should be a breaking release since we need to move away from a single url_map and instead use `url_map_http/url_map_https` either as inputs or managed inside the module.

**Comment by mercuriete** [comment]
thanks @morgante :+1:
